### PR TITLE
Add `.travis.yml`

### PR DESCRIPTION
**Pull request by mamacdon**
Adds a Travis build file that checks all YAML and JSON files for validity.

### CODE REVIEW

**Comment by pradeep-b** [comment]
@mamacdon I presume this is needed for all the branches?

**Comment by mamacdon** [comment]
@pradeep-b Yes, ideally all the branches would have this file. The script I was running to create these Pull Request may've missed a few branches.

**Comment by pradeep-b** [comment]
@mamacdon OK. I see the PR only for master, unless someone has accepted the PRs into the rest of the branches.
BTW, we just added another four branches this week. So will have to fork the repo again to have the complete set.

**Comment by mamacdon** [comment]
@pradeep-b I've opened pull requests against the rest of the branches:

- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/112
- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/113
- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/114
- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/115
- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/116
- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/117
- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/118
- https://github.com/open-toolchain/v1-to-v2-toolchain/pull/119

**Pull request merged**
